### PR TITLE
conf listed twice; removes second (dead) link

### PR DESCRIPTION
**Pull request by ablwr**

### CODE REVIEW

**Comment by ablwr** [comment]
Oh should this go to the forked repo?

**Comment by ross-spencer** [comment]
@ablwr yes please! (I can port this one over there though if it’s easier) (and I need to archive this repo it seems. I hadn’t figured what was best to do before)

**Comment by ablwr** [comment]
If you catch this one up to the fork, you can then transfer ownership? Yeah I dunno best practices here... one moment while I re-commit this on the other.

**Comment by ross-spencer** [comment]
Hi @ablwr your approach is nice! I wish I had done that first time around. I can't successfully do this now without this issue: https://help.github.com/articles/about-repository-transfers/ - what do you reckon? shall I just delete this repo? Would that be terrible?

**Comment by ablwr** [comment]
Ahhh trouble no matter what...

What I would probably do is:

Locally pull digital-preservation-is-people fork
Merge changes found in DPiP master to this one's master
Resolve any conflicts
Then...
Delete DPiP fork
Transfer ownership of this repo to DPiP

Then there is only one! 

Given the amount of followers/watchers on each, I think this is maybe the cleanest approach.

**Comment by ross-spencer** [comment]
Sounds good to me @ablwr. Will be a couple of days but should be able to sort that out pretty soon. Thank you!!

**Comment by ablwr** [comment]
Why aren't you doing karaoke right now??

**Comment by ross-spencer** [comment]
Does singing on my own count? (as i quite literally am!) everyone went home!!! - I think tomorrow might be prime karaoke night :)

**Pull request closed without merging**
